doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    # dbal:
    #     default_connection:       default
    #     connections:
    #         default:
    #             dbname:           williamv_acscom
    #             user:             williamv
    #             password:         tXXz8Jhh4T27gg==
    #             host:             217.182.218.247
    #             server_version:   'mariadb-10.1.41'
    #         # kevin:
    #         #     dbname:           acscom
    #         #     user:             root
    #         #     password:         kevinkevin
    #         #     host:             localhost
    #         #     server_version:   '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
