imports:
    - {resource: admin/}
    # design: 

    # entities:
    #    # List the entity class name you want to manage
    #     - App\Entity\Category
    #     - App\Entity\Product
    #     - App\Entity\Account
    #     - App\Entity\Adress
    #     - App\Entity\Article
    #     - App\Entity\Cart
    #     - App\Entity\Orders
    #     - App\Entity\Price
    #     - App\Entity\ArticleImages
    #     - App\Entity\Review
    #     - App\Entity\Tag
