easy_admin:
   site_name: "LBB's Shop"
   entities:
       # List the entity class name you want to manage
       - App\Entity\Product
       - App\Entity\Category
       - App\Entity\Account
       - App\Entity\Adress
       - App\Entity\Article
       - App\Entity\Cart
       - App\Entity\Orders
       - App\Entity\Price
       - App\Entity\ArticleImages
       - App\Entity\Review
       - App\Entity\Tag
