easy_admin:
  entities:
    Article:
      class:  App\Entity\Article
      list:
        actions:
          - {name: 'edit', icon: 'edit', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      form:
        fields:
          - 'stock'
          - 'size'
          - 'color'
          - 'device'
          - 'product'
      edit:
        fields:
          - 'images'