easy_admin:
  entities:
    Tag:
      class:  App\Entity\Tag
      list:
        actions:
          - {name: 'edit', icon: 'edit', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}